# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "https://cp96304.us-east4.gcp.snowflakecomputing.com"
user = "murnav"
password = "N@veen2021"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
