# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = ECHKCWI.YQ13705
user = murnav
password = N@veen20211
role = ACCOUNTADMIN
warehouse = COMPUTE_WH
database = PC_DBT_DB
schema = DBT_NMURUGESAN
